version: '3.8'

services:
  lection_to_audio:
    build: .
    volumes:
      - ./lections_text_base:/app/lections_text_base
      - ./lections_text_mistral:/app/lections_text_mistral
      - ./lections_audio:/app/lections_audio
      - ./samples:/app/samples
      - ./model_cache:/root/.cache/huggingface
      - ./tts_models:/root/.local/share/tts
    environment:
      - COQUI_TOS_AGREED=1
      - SKIP_XTTS_DOWNLOAD=0
      - FORCE_CPU=1