version: '3.8'

services:
  lection_to_audio:
    build: .
    volumes:
      - ./lections_text_base:/app/lections_text_base
      - ./lections_text_mistral:/app/lections_text_mistral
      - ./lections_audio:/app/lections_audio
      - ./samples:/app/samples
      - ./model_cache:/root/.cache/huggingface
      - ./tts_models:/root/.local/share/tts
      - ./silero_model.pt:/app/silero_model.pt
    environment:
      - COQUI_TOS_AGREED=1
      - SKIP_XTTS_DOWNLOAD=0
      - FORCE_CPU=1
      - PYTHONUNBUFFERED=1
      - NNPACK_IGNORE=1
    deploy:
      resources:
        limits:
          memory: 8G
    restart: unless-stopped
    # Используем healthcheck для проверки статуса контейнера
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/root/.local/share/tts') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s